using NUnit.Framework;
using UnityEngine;

/// <summary>
/// EditMode tests for POIData derived properties (ADR-021).
/// Validates that Floor, Building, and EffectiveName are correctly derived
/// from GameObject naming conventions rather than stored redundantly.
/// </summary>
[TestFixture]
public class POIDataTests
{
    private GameObject _go;
    private POIData _poi;

    [SetUp]
    public void SetUp()
    {
        _go = new GameObject();
        _poi = _go.AddComponent<POIData>();
    }

    [TearDown]
    public void TearDown()
    {
        Object.DestroyImmediate(_go);
    }

    [Test]
    public void Floor_WithValidPrefix_ReturnsFloorLabel()
    {
        _go.name = "[Lantai1] IGD";
        Assert.AreEqual("Lantai 1", _poi.Floor);
    }

    [Test]
    public void Floor_GroundPrefix_ReturnsGround()
    {
        _go.name = "[Ground] Lobby";
        Assert.AreEqual("Ground", _poi.Floor);
    }

    [Test]
    public void Floor_NoPrefix_ReturnsNull()
    {
        _go.name = "SomeRoom";
        Assert.IsNull(_poi.Floor);
    }

    [Test]
    public void Building_AlwaysReturnsConstant()
    {
        Assert.AreEqual("RS Islam Ahmad Yani", _poi.Building);
    }

    [Test]
    public void EffectiveName_FallbackToGameObjectName_WithoutPrefix()
    {
        // No POI SDK component, so EffectiveName falls back to GameObject name
        // minus the floor prefix
        _go.name = "[Lantai2] Radiologi";
        Assert.AreEqual("Radiologi", _poi.EffectiveName);
    }

    [Test]
    public void EffectiveName_NoPrefix_ReturnsFullName()
    {
        _go.name = "Farmasi";
        Assert.AreEqual("Farmasi", _poi.EffectiveName);
    }

    [Test]
    public void PoiId_AutoGenerated_OnReset()
    {
        // Reset is called when component is first added in Editor
        // After AddComponent, Reset should have been called
        Assert.IsFalse(string.IsNullOrEmpty(_poi.poiId),
            "poiId should be auto-generated on Reset");
    }
}
